### PR TITLE
Add-share-dump

### PR DESCRIPTION
**Pull request by brunoborges**

### CODE REVIEW

**Comment by brunoborges** [comment]
@d3r3k can you please review?

**Comment by d3r3kk** [comment]
Consider this a newb question: What does that do? When I ran it on my local before it didn't show any output (perhaps I didn't run it with the appropriate level of verbosity?).

**Comment by brunoborges** [comment]
-Xshare:dump enables Class Data Sharing (CDS).

https://docs.oracle.com/en/java/javase/11/vm/class-data-sharing.html#GUID-7EAA3411-8CF0-4D19-BD05-DF5E1780AA91

**Comment by brunoborges** [comment]
Fixes #16

**Review by d3r3kk — APPROVED** [review]
Thanks for educating me! Approved! 🚢 it. 

My apologies that I had taken this out without asking ahead of time. I had lumped this code in with the `java -version` checks and misunderstood the purpose of it all (and now the mysterious ~5Mb container image size increase has a more likely explanation!!).

**Pull request merged**
