### PR TITLE
Updated to 1ESPipelineTemplates for added security and compliance

### PR DESCRIPTION
**Pull request by jmjaffe37**
Note: the only chagnes are:
1) The added 1ESPipelineTemplates resource
2) The extends statement at the beginning
3) The pools used (we need to use our 1ES agent pools for the templates to work)

### CODE REVIEW

**Comment by jmjaffe37** [comment]
Note: a successful pipeline run has been linked in the thread on MSFT Teams

**Review by karianna — COMMENTED** [review]
I see Ubuntu 20.04 there, should we be using a newer LTS or look to use mariner?

**Comment by jmjaffe37** [comment]
> I see Ubuntu 20.04 there, should we be using a newer LTS or look to use mariner?

We need to use our 1ES Agent pools and 20.04 is the latest LTS version we have set up. 24.04 is coming out in April, so we plan on upgrading to that soon after

**Comment by karianna** [comment]
> > I see Ubuntu 20.04 there, should we be using a newer LTS or look to use mariner?
> 
> The 1ES pipeline templares require us to use our 1ES Agent pools and 20.04 is the latest LTS version we have set up. 24.04 is coming out in April, so we plan on upgrading to that soon after

So no Azure Linux / Mariner option? I'd like to find out why from 1ES that's not on offer if it isn't.

**Comment by jmjaffe37** [comment]
> > > I see Ubuntu 20.04 there, should we be using a newer LTS or look to use mariner?
> > 
> > 
> > The 1ES pipeline templares require us to use our 1ES Agent pools and 20.04 is the latest LTS version we have set up. 24.04 is coming out in April, so we plan on upgrading to that soon after
> 
> So no Azure Linux / Mariner option? I'd like to find out why from 1ES that's not on offer if it isn't.

I think I can change it to mariner2.0 if desired, please leave a thumbs up if this is preferable @karianna

**Comment by jmjaffe37** [comment]
New run using mariner 2.0 pools linked in teams

**Comment by jmjaffe37** [comment]
Now using separate windows pools for SDL analysis

**Comment by Luigi96** [comment]
LGTM

**Review by d3r3kk — APPROVED** [review]
🚢it

**Pull request merged**
