### PR TITLE
Change images to run as non-root user by default

### PR DESCRIPTION
**Pull request by yoshioterada**
Currently, the container images are running as root user as follows. 
And I hope that it will run as a non-root user by default for security purposes.

The following log will be seen at the startup time of Spring Boot.
"***/app/app.jar started by root***" was wrote.

```text
2022-10-20 17:32:02.045  INFO 1 --- [main] com.yoshio3.HelloSampleApplication : 
Starting HelloSampleApplication v0.0.1-SNAPSHOT using Java 17.0.4.1 on 7446eed214e7 
with PID 1 (/app/app.jar started by root in /app)
```

If we use this fix, the application will run as a non-root user ("javauser") by default as follows. 
"***/app/app.jar started by javauser***" was wrote.

```text
2022-10-20 17:30:28.103  INFO 1 --- [main] com.yoshio3.HelloSampleApplication : 
Starting HelloSampleApplication v0.0.1-SNAPSHOT using Java 17.0.4.1 on 9a2adf159e03 
with PID 1 (/app/app.jar started by javauser in /app)
```

To run the container more securely, this pull request will be useful. And if this pull request is not included, every user needs to write a look like the following Dockerfile to run as a non-root user

```Dockerfile
##################################################################
# Stage 1: Create User and Group
##################################################################
FROM mcr.microsoft.com/cbl-mariner/base/core:2.0 AS CREATE-DEPENDS-FILES

RUN mkdir /staging \
    && mkdir /staging/etc \
    && tdnf install -y  --releasever=2.0 shadow-utils \
    && groupadd --system -g 101 java-app \
    && useradd -u 101 -g java-app --shell /bin/false --home-dir /dev/null --system javausers \
    && tdnf clean all \
   # Copy user/group info to staging
   && cp /etc/passwd /staging/etc/passwd \
   && cp /etc/group /staging/etc/group

##################################################################
# Stage 2: Create User and Group
##################################################################
FROM mcr.microsoft.com/openjdk/jdk:17-distroless

COPY --from=CREATE-DEPENDS-FILES /staging/ /
USER javauser
WORKDIR /app
ENV LANG='ja_JP.UTF-8' LANGUAGE='ja_JP:ja' LC_ALL='ja_JP.UTF-8'
ENV TZ='Asia/Tokyo'
ENV JAVA_HOME=/app

COPY ./target/hello-sample-0.0.1-SNAPSHOT.jar app.jar

ENTRYPOINT ["java","-Xmx1g","-XX:+UseParallelGC","-XX:MaxRAMPercentage=75","-jar","/app/app.jar"]
EXPOSE 8080
```

### CODE REVIEW

**Comment by karianna** [comment]
Thank you for the PR and the suggestion.  We'll discuss it internally but I suspect that this particular implementation (of adding a MSFT provided `javauser` will be seen as something that the customer should choose to do themselves (and not have it supplied for them)

@brunoborges - thoughts?

**Comment by brunoborges** [comment]
Some people may want to run a server on port 80 inside the container. And for that to work, the JVM must be running as root. So, to cover all scenarios, we've decided to go with root.

But as Martijn pointed out, customers are more than welcome to customize their layer as they write their own Dockerfiles, and configure a non-root user.

Indeed, our documentation does not cover this well, and we should at the very least, explain which user it runs by default, and how to customize that on a downstream Docker image layer built by customers.

**Comment by yoshioterada** [comment]
@karianna san, @brunoborges san
First, Thank you so much for your messages and reply.

> the customer should choose to do themselves (and not have it supplied for them

Yes, if the customer can choose the `USER` that they would like to configure, it is better.
However, if we use the base image as "CBL-Mariner," it is difficult now and it will fail by default as follows.

At first, I created the following Dockerfile and build the images.

```Dockerfile
FROM mcr.microsoft.com/openjdk/jdk:17-distroless

USER javauser
WORKDIR /app
ENV LANG='ja_JP.UTF-8' LANGUAGE='ja_JP:ja' LC_ALL='ja_JP.UTF-8'
ENV TZ='Asia/Tokyo'
ENV JAVA_HOME=/app

COPY ./target/hello-sample-0.0.1-SNAPSHOT.jar app.jar

ENTRYPOINT ["java","-Xmx1g","-XX:+UseParallelGC","-XX:MaxRAMPercentage=75","-jar","/app/app.jar"]
EXPOSE 8080 
```

Then, If I run the above images, the following error happens.

```bash
> docker run -p 8080:8080 -it tyoshio2002/sample1:1.1                          
docker: Error response from daemon: unable to find user javauser: no matching entries in passwd file.
```
Even though the container builds success, the above "javauser" was not added to the container. Because the "CBL-Mariner" image doesn't have "useradd,groupadd" command by default and failed. 
And there was not enough info to add the user. So I asked the products team of "CBL-Mariner," and I got it. So it means that it is difficult for customers to customize the USER now.

Perhaps, many users would like to run the container as "non-root" users because it is the best practice that @jdubois san mentioned above.
And EVERY user will face the above problem since now. And the user will ask the same things every time without the official documents.

```
RUN mkdir /staging \
    && mkdir /staging/etc \
    && tdnf install -y  --releasever=2.0 shadow-utils \
    && groupadd --system -g 101 java-app \
    && useradd -u 101 -g java-app --shell /bin/false --home-dir /dev/null --system javausers \
    && tdnf clean all \
   # Copy user/group info to staging
   && cp /etc/passwd /staging/etc/passwd \
   && cp /etc/group /staging/etc/group
```

To avoid confusion and every user must do the above, I created the pull request.

If you decide to run the container as root, at least we should explain how to customize the USER in the official document. And I would like to ask you to do it please.

BTW, I already wrote it by Japanese as follows.
https://qiita.com/yoshioterada/items/93260d9eec501f2ffeba

**Comment by karianna** [comment]
@yoshioterada - As a side note - the GH Actions are failing.  I'm not sure if this is due to the #comment you've added in the middle of the user setup logic in the PR.

**Comment by karianna** [comment]
*if* we make the change then I think moving to non-root as a default will be a breaking change for existing customers who are using these images, something we need to keep in mind.

**Comment by yoshioterada** [comment]
@karianna san,

For the GitHub Action failed issue.

It may be due to the workflow as a `build-images.yml` file, not from my modification.
On the above YAML file, the following was written.

```bash
docker build 
-t mcr.microsoft.com/openjdk/jdk:${{ matrix.jdkversion }}-${{ matrix.baseimage }} 
-f ./docker/${{ matrix.baseimage }}/Dockerfile.msopenjdk-${{ matrix.jdkversion }}-jdk 
./docker/${{ matrix.baseimage }}/ 
--build-arg INSTALLER_IMAGE=${{ env.INSTALLER_IMAGE }} 
--build-arg INSTALLER_TAG=${{ matrix.installer_tag }} 
--build-arg BASE_IMAGE=${{ env.BASE_IMAGE }} 
--build-arg BASE_TAG=${{ matrix.base_tag }}
```

And from the result of the GitHub Action, the following was invoked.

```bash
docker build 
-t mcr.microsoft.com/openjdk/jdk:11-distroless 
-f ./docker/distroless/Dockerfile.msopenjdk-11-jdk 
./docker/distroless/ 
--build-arg INSTALLER_IMAGE= 
--build-arg INSTALLER_TAG=2.0 
--build-arg BASE_IMAGE= 
--build-arg BASE_TAG=2.0
```

At that time, the following error happened.

```text
Step 1/18 : ARG INSTALLER_IMAGE="mcr.microsoft.com/cbl-mariner/base/core"
Step 2/18 : ARG INSTALLER_TAG="2.0"
Step 3/18 : ARG BASE_IMAGE="mcr.microsoft.com/cbl-mariner/distroless/base"
Step 4/18 : ARG BASE_TAG="2.0"
invalid reference format
Step 5/18 : FROM ${INSTALLER_IMAGE}:${INSTALLER_TAG} AS installer
```

In my local environment, I tried to execute the above command, then the same error happened.

However, if I invoke the following command that includes `--build-arg IMAGE="mcr.microsoft.com/cbl-mariner/base/core"` by hand, it succeeded the build. 
It means that the reference of the `INSTALLER_IMAGE` definition as `${{ env.INSTALLER_IMAGE }}`, it may not be able to get during the GitHub Actions. (Now I'm investigating the reason....)

```bash
docker build 
-t mcr.microsoft.com/openjdk/jdk:11-mariner 
-f ./docker/mariner/Dockerfile.msopenjdk-11-jdk 
./docker/mariner/ 
--build-arg IMAGE="mcr.microsoft.com/cbl-mariner/base/core" 
--build-arg TAG='2.0'
```

And also, if I updated the "Java Version" to the latest version in the `build-all-images.sh` file, I could succeed in building all of the images in the local environment.

**Comment by karianna** [comment]
@d3r3kk - Can we get one of the infra folks to look at this?

**Comment by brunoborges** [comment]
@yoshioterada do you have some customer feedback to share, where they have concrete security concerns about this image being root by default?

**Comment by jdubois** [comment]
There is plenty of documentation telling not to run containers as root, but probably the best argument is that you cannot run containers as root on OpenShift ( see https://dev.to/ksingh7/allow-containers-to-run-as-root-on-openshift-4-hack-3gp7 for example), so our image wouldn't work on ARO.

**Comment by yoshioterada** [comment]
Dear Bruno-san.

I'm sorry that I don't have any customers now.
Because I knew that the Container Application should run as "non-root" user as a best practice.
And before I informed the customer, I noticed and created the pull request by myself.
So currently, there is no actual customer feedback. 
As Julien-san mentioned use case of deploying to OpenShift will be one of issues.

And today, I noticed one more thing. 
Thus I submitted two very important modifications.

---
After applying this pull request, the application will run as "javauser". However, no directory has "write permission".

If one Java Application tries to write some file in the deployment directory, it will fail. Because it is owned by the root user.

So to write some files from the application, I added a
 default directory, which is owned by the "javauser"

So if the user deployment their application under the "/app" directory. The application will run without a problem.

If the user uses the Mariner core image, then there is "chown" command in the container images.
So the user can create any directory and can change the owner.

However, the "distress image" doesn't have the "chown" command on the image or shell.

So we should mention the restriction for "distress image" users.

For example, the following explanation will be needed.

***If you use the "distress image", please copy the artifact file under the "/app" directory with the following option.***

```
COPY --chown=2000:2000 artifact.jar /app/
```

**Comment by d3r3kk** [comment]
> @d3r3kk - Can we get one of the infra folks to look at this?

Created a Bug for the infra team to follow up on.

**Comment by brunoborges** [comment]
Thanks @yoshioterada.

I've submitted PR #57 as a solution to this problem. The intent is that images will continue to run as root by default, but with the _option_ that the user/customer may run as a non-root user, with the `app` account.

Let me know what you think of that.

**Review by brunoborges — COMMENTED** [review]
It is likely we will close this one in favour of #57. By adding a non-root user to the images, customers will have the option to run their applications as non-root.

**Comment by yoshioterada** [comment]
Daer @brunoborges san,

I saw the new pull request as follows. 

[GitHub : Add non-root user 'app' to all images #57](https://github.com/microsoft/openjdk-docker/pull/57)

If you provide a default Application "app" user and the directory owned by the user, it may be helpful for the developers. 

There is no info now on [learn.microsoft.com](https://learn.microsoft.com/). So please write an explanation of how to use the "app" user in the customer's application.

Then please close this pull request.

**Comment by brunoborges** [comment]
Can you please test that proposal?

**Pull request closed without merging**
